# Generated by Django 4.0.3 on 2022-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=8)),
                ('email', models.EmailField(max_length=25)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
