# Generated by Django 4.0.3 on 2022-05-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
