# Generated by Django 4.0.3 on 2022-05-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_registration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.TextField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
