from django.urls import path
from .import views

urlpatterns = [
    path('', views.home1,name="home1"),
    path('home/', views.home,name="home"),
    path('login/', views.login,name="login"),
    path('stafflogin/', views.stafflogin,name="stafflogin"),
    path('managerlogin/', views.managerlogin,name="managerlogin"),
    path('asstmanagerlogin/', views.asstmanagerlogin,name="asstmanagerlogin"),
    path('admin1/', views.admin,name="admin"),
    path('targets/', views.targets,name="targets"),
     path('forgot/', views.forgot,name="forgot"),
    path('edit/', views.edit,name="edit"),
    path('reports/', views.reports,name="reports"),
    path('attendance/', views.attendance,name="attendance"),
    path('attendancenew/', views.attendancenew,name="attendancenew"),
    path('staffs/', views.staffs,name="staffs"),
    path('reset/', views.reset,name="reset"),
    path('notifications/', views.notifications,name="notifications"),
    path('index4/', views.index4),
    path('managerhome/', views.managerhome,name="managerhome"),
    path('managerstaff/', views.managerstaff,name="managerstaff"),
    path('managerprofiles/', views.managerprofiles,name="managerprofiles"),
    path('asstmanagerprofiles/', views.asstmanagerprofiles,name="asstmanagerprofiles"),
    path('adminclerkprofile/', views.adminclerkprofile,name="adminclerkprofile"),
    path('staffprofile/', views.staffprofile,name="staffprofile"),
    path('clerkprofile/', views.clerkprofile,name="clerkprofile"),
    path('schemes/', views.schemes,name="schemes"),
    path('customers/', views.customers,name="customers"),
    path('adminmanager/', views.adminmanager,name="adminmanager"),
    path('index7/', views.index7,name="tom"),
    path('table/', views.table,name="table"),
    path('staffhome/', views.staffhome,name="staffhome"),
    path('delete/<int:id>', views.delete,name="delete"),
    path('update/<int:id>', views.update,name="update"),
    path('mammlogin/',views.mammlogin,name="maamlogin"),
    path('logout/',views.logout,name="logout"),
    path('home/forgot/',views.forgot,name="forgot"),
    path('registration/',views.registration,name="registration"),
    path('ad asst ma profile/',views.adasstmaprofile,name="ad asst ma profile"),
    path('maamprofile/',views.maamprofile,name="maamprofile"),
    path('maamproduct/',views.maamproduct,name="maamproduct"),
    path('maamshow/',views.maamshow,name="maamshow"),

]
